version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: spectatore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spectatore
    ports:
      - "5432:5432"
    volumes:
      - spectatore_pgdata:/var/lib/postgresql/data
volumes:
  spectatore_pgdata:
